spring:
  application:
    name: erp-light

  profiles:
    active: dev

  datasource:
    url: jdbc:postgresql://localhost:5432/erp_dummy
    username: dummy
    password: dummy
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
